/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleGuideHomepageRouteImport } from './routes/style-guide-homepage'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as FansRouteImport } from './routes/fans'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromoWorldCupRouteImport } from './routes/promo.world-cup'
import { Route as LeagueSlugRouteImport } from './routes/league.$slug'
import { Route as EventIdRouteImport } from './routes/event.$id'

const StyleGuideHomepageRoute = StyleGuideHomepageRouteImport.update({
  id: '/style-guide-homepage',
  path: '/style-guide-homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FansRoute = FansRouteImport.update({
  id: '/fans',
  path: '/fans',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoWorldCupRoute = PromoWorldCupRouteImport.update({
  id: '/promo/world-cup',
  path: '/promo/world-cup',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueSlugRoute = LeagueSlugRouteImport.update({
  id: '/league/$slug',
  path: '/league/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/fans': typeof FansRoute
  '/style-guide': typeof StyleGuideRoute
  '/style-guide-homepage': typeof StyleGuideHomepageRoute
  '/event/$id': typeof EventIdRoute
  '/league/$slug': typeof LeagueSlugRoute
  '/promo/world-cup': typeof PromoWorldCupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/fans': typeof FansRoute
  '/style-guide': typeof StyleGuideRoute
  '/style-guide-homepage': typeof StyleGuideHomepageRoute
  '/event/$id': typeof EventIdRoute
  '/league/$slug': typeof LeagueSlugRoute
  '/promo/world-cup': typeof PromoWorldCupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/fans': typeof FansRoute
  '/style-guide': typeof StyleGuideRoute
  '/style-guide-homepage': typeof StyleGuideHomepageRoute
  '/event/$id': typeof EventIdRoute
  '/league/$slug': typeof LeagueSlugRoute
  '/promo/world-cup': typeof PromoWorldCupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/fans'
    | '/style-guide'
    | '/style-guide-homepage'
    | '/event/$id'
    | '/league/$slug'
    | '/promo/world-cup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/fans'
    | '/style-guide'
    | '/style-guide-homepage'
    | '/event/$id'
    | '/league/$slug'
    | '/promo/world-cup'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/fans'
    | '/style-guide'
    | '/style-guide-homepage'
    | '/event/$id'
    | '/league/$slug'
    | '/promo/world-cup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  FansRoute: typeof FansRoute
  StyleGuideRoute: typeof StyleGuideRoute
  StyleGuideHomepageRoute: typeof StyleGuideHomepageRoute
  EventIdRoute: typeof EventIdRoute
  LeagueSlugRoute: typeof LeagueSlugRoute
  PromoWorldCupRoute: typeof PromoWorldCupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-guide-homepage': {
      id: '/style-guide-homepage'
      path: '/style-guide-homepage'
      fullPath: '/style-guide-homepage'
      preLoaderRoute: typeof StyleGuideHomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fans': {
      id: '/fans'
      path: '/fans'
      fullPath: '/fans'
      preLoaderRoute: typeof FansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/world-cup': {
      id: '/promo/world-cup'
      path: '/promo/world-cup'
      fullPath: '/promo/world-cup'
      preLoaderRoute: typeof PromoWorldCupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$slug': {
      id: '/league/$slug'
      path: '/league/$slug'
      fullPath: '/league/$slug'
      preLoaderRoute: typeof LeagueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  FansRoute: FansRoute,
  StyleGuideRoute: StyleGuideRoute,
  StyleGuideHomepageRoute: StyleGuideHomepageRoute,
  EventIdRoute: EventIdRoute,
  LeagueSlugRoute: LeagueSlugRoute,
  PromoWorldCupRoute: PromoWorldCupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
